# Generated by Django 3.1.5 on 2021-05-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='small_description',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default='', upload_to='imgsite/images'),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
