# Generated by Django 3.1.5 on 2021-05-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgsite', '0003_images_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='images',
            name='category',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.RemoveField(
            model_name='images',
            name='small_description',
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_description', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='imgsite/images')),
                ('publications', models.ManyToManyField(to='imgsite.Images')),
            ],
            options={
                'ordering': ['small_description'],
            },
        ),
    ]
