# Generated by Django 3.1.5 on 2021-05-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgsite', '0004_auto_20210520_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={},
        ),
        migrations.AddField(
            model_name='images',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(default='', upload_to='imgsite/images'),
        ),
        migrations.AddField(
            model_name='images',
            name='small_description',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
