# Generated by Django 3.1.5 on 2021-05-11 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videosite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Videos',
        ),
    ]
