# Generated by Django 3.1.5 on 2021-05-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0002_auto_20210505_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='body',
            field=models.CharField(default='', max_length=15),
        ),
    ]
