# Generated by Django 3.1.5 on 2021-05-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0003_data_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='data',
            name='vision',
        ),
        migrations.AddField(
            model_name='data',
            name='image',
            field=models.ImageField(default='', upload_to='helloapp/images'),
        ),
        migrations.AddField(
            model_name='data',
            name='image_title1',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='data',
            name='image_title2',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='data',
            name='image_title3',
            field=models.CharField(default='', max_length=15),
        ),
    ]
