# Generated by Django 3.1.5 on 2021-05-06 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0005_auto_20210506_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='image',
            new_name='image1',
        ),
    ]
